version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
    versioning-strategy: increase
    ignore:
      - dependency-name: "zod"
        versions:
          - ">=4.0.0"
